<?php

use Drupal\node\Entity\Node;

/**
 * Implements hook_theme().
 */
function recipes_theme($existing, $type, $theme, $path) {
  return [
    'recipe_preview' => [
      'variables' => [
        'recipe' => NULL,
      ],
      'template' => 'recipe-preview',
    ],
  ];
}

/**
 * Implements hook_views_query_alter().
 */
function recipes_views_query_alter($view, $query) {
  // Remove ingredients from the main admin content listing.
  
  if ($view->id() == 'content') {
    // Add a condition to exclude your 'ingredient' machine name
    $query->addWhere(1, 'node_field_data.type', 'recipes_ingredient', '!=');
  }
}

/**
 * Implements hook_entity_predelete().
 */
function recipes_entity_predelete(\Drupal\Core\Entity\EntityInterface $entity) {
  // Remove all the ingredients associated with a recipe.

  // Only act if we are deleting a 'recipe' node.
  if ($entity->getEntityTypeId() === 'node' && $entity->bundle() === 'recipes_recipe') {
    
    // Find all 'ingredient' nodes that reference this recipe.
    $ingredients = $entity->get('field_recipes_ingredients')->referencedEntities();

    if (!empty($ingredients)) {
      // Delete the referenced ingredient nodes.
      foreach ($ingredients as $ingredient) {
        $ingredient->delete();
      }
    }
  }
}