name: Build and Push Drupal Image

on:
 push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set lower case owner name
        run: |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          # This tags the image as 'latest' and with the specific Git commit hash
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO }}:latest
            ${{ env.REGISTRY }}/${{ env.REPO }}:${{ github.sha }}
