name: Build and Push Images

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generates lowercase names to completely avoid GitHub repository capitalization bugs
      - name: Set lower case owner and image names
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "DRUPAL_IMAGE=${{ env.REGISTRY }}/$REPO_LOWER-drupal" >> $GITHUB_ENV
          echo "NGINX_IMAGE=${{ env.REGISTRY }}/$REPO_LOWER-nginx" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- 1. BUILD DRUPAL IMAGE ---
      - name: Build and push Drupal image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./.docker/prod/drupal.Dockerfile
          push: true
          tags: |
            ${{ env.DRUPAL_IMAGE }}:latest
            ${{ env.DRUPAL_IMAGE }}:${{ github.sha }}

      # --- 2. BUILD NGINX IMAGE ---
      - name: Build and push Nginx Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./.docker/prod/nginx.Dockerfile
          push: true
          tags: |
            ${{ env.NGINX_IMAGE }}:latest
            ${{ env.NGINX_IMAGE }}:${{ github.sha }}
